### ISSUE TITLE
Horizontal Scrolling

### ISSUE THREAD

**Issue by praven07** [triniwiz/nativescript-fancy-list-view#1]
Is it possible to make it scroll horizontally?

**Comment by triniwiz** [comment]
You tried changing the orientation prop to horizontal?

**Comment by praven07** [comment]
Yes I tried that. This is the code I used but didn't get it to work.

    <FancyListView [items]="items" 
		        orientation="horizontal" 
			itemWidth="100%" 
			itemHeight="100%">  
		<ng-template let-i="index" let-item="item">  
		      <GridLayout width="100%" height="100%">  
		           <Label [text]="item"></Label>  
		      </GridLayout>  
		</ng-template>
    </FancyListView>

**Comment by triniwiz** [comment]
Fixed in the latest release
